version: '3.1'
services:
  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    container_name: database_ponderada

  web_app:
    build: .
    restart: always
    network_mode: host
    ports:
      - 5000:5000
    container_name: web_app_ponderada